### PR TITLE
Update with new hawk-pack

### PR DESCRIPTION
**Pull request by iliailia**
This change allows vector operations to mutate a vector store. It's needed for #618.

### CODE REVIEW

**Comment by bgillesp** [comment]
What do the `eval_distance` and `eval_distance_batch` functions need to mutate the vector store for?  My feeling is that these should be considered "read-only" functions on the vector stores, and any state that does need to be updated should be stored somewhere else, or the updates should be handled outside these functions.  (I'm guessing it's an MPC/networking thing?)

**Comment by iliailia** [comment]
> What do the `eval_distance` and `eval_distance_batch` functions need to mutate the vector store for? My feeling is that these should be considered "read-only" functions on the vector stores, and any state that does need to be updated should be stored somewhere else, or the updates should be handled outside these functions. (I'm guessing it's an MPC/networking thing?)

It's related to sessions. Many low-level MPC functions mutate PRNG within a `Session` object to generate randomness, zero-shares etc. If we want to generate as little PRF as possible (in other words, do as many operations as possible within a single Session), then we can attach a session to a vector store and invoke it when needed. This is what Dragos did here #618.

**Comment by bgillesp** [comment]
Okay, I understand now.  The issue is that the `VectorStore` trait represents an object that doesn't just store the vectors, but is also responsible for processing the vectors, hence the MPC/networking state creeps in.  Right now it can't easily represent the idea that "vectors are read-only" for certain operations, because the mutability has to reflect the entire state, including anything on top needed for handling the processing.

I have an inkling that things might be a bit cleaner if we logically separate this into a separate object that handles interpreting/processing the HNSW graphs and vectors using the HNSW logic, so that the vector and graph data are properly independent of the processing -- but I think that's refactoring for another PR if we decide it's necessary.

**Review by bgillesp — APPROVED** [review]
Changes look fine -- but interested if you have thoughts on the potential refactoring I mentioned above to decouple the operation state/logic from the underlying data structures.

**Comment by iliailia** [comment]
> Okay, I understand now. The issue is that the `VectorStore` trait represents an object that doesn't just store the vectors, but is also responsible for processing the vectors, hence the MPC/networking state creeps in. Right now it can't easily represent the idea that "vectors are read-only" for certain operations, because the mutability has to reflect the entire state, including anything on top needed for handling the processing.
> 
> I have an inkling that things might be a bit cleaner if we logically separate this into a separate object that handles interpreting/processing the HNSW graphs and vectors using the HNSW logic, so that the vector and graph data are properly independent of the processing -- but I think that's refactoring for another PR if we decide it's necessary.

We can add a mutable evaluator struct argument to all functions that might need interaction. This struct will contain all the mutable parts necessary for evaluation and can be specific for a certain implementation of `VectorStore` via traits.

**Comment by dkales** [comment]
yeah I also think some struct like an IOContext or similar that is passed to functions that need it seems better

**Comment by iliailia** [comment]
> yeah I also think some struct like an IOContext or similar that is passed to functions that need it seems better

Got it, let me do it in some future PR

**Pull request merged**
